version: '2'
services:
  node-red:
    build: ./node-red
    depends_on:
    - sense-hat
    expose:
    - "80"
    restart: always
    volumes:
    - 'resin-data:/data'
  sense-hat:
    build: ./sense-hat
    cap_add:
    - SYS_RAWIO
    devices:
    - "/dev/gpiomem:/dev/gpiomem"
    - "/dev/gpiochip0:/dev/gpiochip0"
    - "/dev/gpiochip1:/dev/gpiochip1"
    expose:
    - "8080"
    init: true
    labels:
      io.resin.features.dbus: '1'
    volumes:
    - 'resin-data:/data'
volumes:
  resin-data: