version: '2'
services:
  node-red:
    build: ./node-red
    cap_add:
    - SYS_RAWIO
    devices:
    - "/dev/gpiochip0:/dev/gpiochip0"
    - "/dev/gpiochip1:/dev/gpiochip1"
    - "/dev/gpiomem:/dev/gpiomem"
    - "/dev/i2c-1:/dev/i2c-1"
    - "/dev/spidev0.0:/dev/spidev0.0"
    - "/dev/spidev0.1:/dev/spidev0.1"
    ports:
    - "80:1880"
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
    network_mode: host
    restart: always
    volumes:
    - 'resin-data:/data'
  sense-hat-data-logger:
    cap_add:
    - SYS_RAWIO
    build: ./sense-hat-data-logger
    devices:
    - "/dev/fb0:/dev/fb0"
    - "/dev/fb1:/dev/fb1"
    - "/dev/fd:/dev/fd"
    - "/dev/ttyAMA0:/dev/ttyAMA0"
    - "/dev/ttyS0:/dev/ttyS0"
    - "/dev/ttyprintk:/dev/ttyprintk"
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.firmware: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
    network_mode: host
    restart: always
    volumes:
    - 'resin-data:/usr'
volumes:
  resin-data: