version: '2'
services:
  node-red:
    build: ./node-red
    cap_add:
    - SYS_RAWIO
    devices:
    - '/dev/fb0:/dev/fb0'
    ports:
    - "80:1880"
    labels:
      io.resin.features.kernel-modules: '1'
      io.resin.features.dbus: '1'
      io.resin.features.supervisor-api: '1'
    restart: always
    volumes:
    - 'resin-data:/data'
volumes:
  resin-data: